import { describe, expect, it, vi } from 'vitest'
import { decide, pending, unsigned } from '~~/.claude/hooks/pr-guard.mjs'

const ask = {
	head: () => 'claude/issue-292-m5eszm',
	dirty: () => '',
	unpushed: () => '',
	check: () => ({ code: 0, log: '' }),
}

const create = (tool_input = {}) => ({
	tool_name: 'mcp__github__create_pull_request',
	tool_input: {
		title: 'x',
		head: 'claude/issue-292-m5eszm',
		base: 'main',
		body: '## やったこと\n\n- x',
		...tool_input,
	},
})

const denied = (input, extra) => decide(input, { ...ask, ...extra })?.deny ?? null

describe('decide', () => {
	it('条件が揃った作成は通し、ラベルを付けるよう伝える', () => {
		expect(decide(create(), ask)).toEqual({ context: '作成したら agent ラベルを付ける' })
	})

	it('欠いた条件を理由に止める', () => {
		expect(denied(create(), { head: () => 'main' })).toMatch('main から PR は出せない')
		expect(denied(create({ head: 'other' }))).toMatch('作業ツリー')
		expect(denied(create({ base: 'release' }))).toMatch('base は main')
		expect(denied(create(), { dirty: () => ' M app/x.vue' })).toMatch('app/x.vue')
		expect(denied(create(), { unpushed: () => 'origin/x が無い' })).toMatch('push していない')
		expect(denied(create(), { head: () => '' })).toMatch('読めない')
		expect(denied(create(), { dirty: () => null })).toMatch('読めない')
		expect(denied(create({ body: '- x' }))).toMatch('型で書く')
		expect(denied(create({ body: '## やったこと\n\n<!-- x -->' }))).toMatch('型で書く')
		expect(
			denied(create({ body: '## 判断してほしいこと\n\n- x\n\n## やったこと\n\n- y' })),
		).toMatch('draft')
	})

	it('CI が打つものを通し、落ちたら出力を添えて止める', () => {
		const check = vi.fn((name) => ({ code: name === 'test' ? 1 : 0, log: 'x\n1 failed' }))
		expect(denied(create(), { check })).toMatch('1 failed')
		expect(check.mock.calls.map(([name]) => name)).toEqual(['lint', 'test'])
	})

	it('作成以外は条件を測らず、他のツールは見ない', () => {
		const update = { tool_name: 'mcp__github__update_pull_request', tool_input: { body: 'x' } }
		expect(decide(update, { ...ask, head: () => 'main' })).toBeNull()
		expect(decide({ tool_name: 'mcp__github__merge_pull_request' }, ask)).toBeNull()
		expect(decide({ tool_name: 'Bash', tool_input: { command: 'x' } }, ask)).toBeNull()
	})
})

describe('pending', () => {
	it('判断の節に中身があるときだけ残りとみなす', () => {
		expect(
			pending('## 判断してほしいこと\n\n<!-- 無ければ消す -->\n\n## やったこと\n\n- y'),
		).toBe(false)
		expect(pending('## やったこと\n\n- 判断してほしいこと')).toBe(false)
	})

	it('判断が残ったまま更新で ready にするのを止める', () => {
		const update = (tool_input) => ({
			tool_name: 'mcp__github__update_pull_request',
			tool_input,
		})
		expect(denied(update({ draft: false, body: '## 判断してほしいこと\n\n- x' }))).toMatch(
			'draft',
		)
		expect(denied(update({ draft: false }))).toBeNull()
	})

	it('draft なら判断が残っていても出せる', () => {
		const body = '## 判断してほしいこと\n\n- x\n\n## やったこと\n\n- y'
		expect(denied(create({ body, draft: true }))).toBeNull()
	})
})

describe('unsigned', () => {
	it('末尾の署名と、その上の区切りを落とす', () => {
		expect(
			unsigned('## やったこと\n\n- x\n\n---\n_Generated by [Claude Code](https://a)_'),
		).toBe('## やったこと\n\n- x')
		expect(
			unsigned(
				'- x\n\n🤖 Generated with [Claude Code](https://a)\n\nhttps://claude.ai/code/session_1',
			),
		).toBe('- x')
		expect(unsigned('- x\n\nCo-Authored-By: Claude Opus 5 <noreply@anthropic.com>')).toBe('- x')
	})

	it('署名の無い本文は触らない', () => {
		expect(unsigned('- x\n\n---\n\n- y')).toBeNull()
		expect(unsigned('')).toBeNull()
	})

	it('署名の綴りに触れた本文の行は落とさない', () => {
		expect(unsigned('Generated by [Claude Code](https://a) と書いた\n\n- x')).toBeNull()
		expect(unsigned('## やったこと\n\n- Generated with [Claude Code] の行を落とす')).toBeNull()
		expect(unsigned('## やったこと\n\n* Generated with [Claude Code] の綴りを直す')).toBeNull()
	})
})
